function countClicks(value) {
  if (value == null) {
    return 0;
  }
  return value[0];
}

function rightClicksCount(value) {
  if (value == null) {
    return 0;
  }
  return value[1];
}

function wrongClicksCount(value) {
  if (value == null) {
    return 0;
  }
  return value[2];
}
const cards = [
  ['Action', 'Colors', 'Animals', 'Food', 'Clothes', 'Emotions', 'Home', 'Nature'],
  [
    {
      word: 'cry',
      translation: 'плакать',
      image: 'img/cry.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('cry'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('cry'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('cry'))),
      audioSrc: 'audio/cry.mp3',
    },
    {
      word: 'dance',
      translation: 'танцевать',
      image: 'img/dance.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('dance'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('dance'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('dance'))),
      audioSrc: 'audio/dance.mp3',

    },
    {
      word: 'dive',
      translation: 'нырять',
      image: 'img/dive.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('dive'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('dive'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('dive'))),
      audioSrc: 'audio/dive.mp3',
    },
    {
      word: 'draw',
      translation: 'рисовать',
      image: 'img/draw.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('draw'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('draw'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('draw'))),
      audioSrc: 'audio/draw.mp3',
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      image: 'img/fish.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('fish'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('fish'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('fish'))),
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'fly',
      translation: 'летать',
      image: 'img/fly.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('fly'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('fly'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('fly'))),
      audioSrc: 'audio/fly.mp3',
    },
    {
      word: 'hug',
      translation: 'обнимать',
      image: 'img/hug.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('hug'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('hug'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('hug'))),
      audioSrc: 'audio/hug.mp3',
    },
    {
      word: 'jump',
      translation: 'прыгать',
      image: 'img/jump.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('jump'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('jump'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('jump'))),
      audioSrc: 'audio/jump.mp3',
    },
  ],
  [
    {
      word: 'red',
      translation: 'красный',
      image: 'img/red.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('red'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('red'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('red'))),
      audioSrc: 'audio/red.mp3',
    },
    {
      word: 'blue',
      translation: 'синий',
      image: 'img/blue.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('blue'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('blue'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('blue'))),
      audioSrc: 'audio/blue.mp3',
    },
    {
      word: 'yellow',
      translation: 'желтый',
      image: 'img/yellow.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('yellow'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('yellow'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('yellow'))),
      audioSrc: 'audio/yellow.mp3',
    },
    {
      word: 'green',
      translation: 'зеленый',
      image: 'img/green.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('green'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('green'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('green'))),
      audioSrc: 'audio/green.mp3',
    },
    {
      word: 'orange',
      translation: 'оранжевый',
      image: 'img/orange.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('orange'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('orange'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('orange'))),
      audioSrc: 'audio/orange.mp3',
    },
    {
      word: 'white',
      translation: 'белый',
      image: 'img/white.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('white'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('white'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('white'))),
      audioSrc: 'audio/white.mp3',
    },
    {
      word: 'purple',
      translation: 'фиолетовый',
      image: 'img/purple.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('purple'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('purple'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('purple'))),
      audioSrc: 'audio/purple.mp3',
    },
    {
      word: 'pink',
      translation: 'розовый',
      image: 'img/pink.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('pink'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('pink'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('pink'))),
      audioSrc: 'audio/pink.mp3',
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      image: 'img/cat.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('cat'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('cat'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('cat'))),
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      image: 'img/chick.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('chick'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('chick'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('chick'))),
      audioSrc: 'audio/chick.mp3',
    },
    {
      word: 'chicken',
      translation: 'курица',
      image: 'img/chicken.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('chicken'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('chicken'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('chicken'))),
      audioSrc: 'audio/chicken.mp3',
    },
    {
      word: 'dog',
      translation: 'собака',
      image: 'img/dog.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('dog'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('dog'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('dog'))),
      audioSrc: 'audio/dog.mp3',
    },
    {
      word: 'horse',
      translation: 'лошадь',
      image: 'img/horse.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('horse'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('horse'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('horse'))),
      audioSrc: 'audio/horse.mp3',
    },
    {
      word: 'pig',
      translation: 'свинья',
      image: 'img/pig.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('pig'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('pig'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('pig'))),
      audioSrc: 'audio/pig.mp3',
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      image: 'img/rabbit.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('rabbit'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('rabbit'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('rabbit'))),
      audioSrc: 'audio/rabbit.mp3',
    },
    {
      word: 'sheep',
      translation: 'овца',
      image: 'img/sheep.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('sheep'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('sheep'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('sheep'))),
      audioSrc: 'audio/sheep.mp3',
    },
  ],
  [
    {
      word: 'tomato',
      translation: 'помидор',
      image: 'img/tomato.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('tomato'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('tomato'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('tomato'))),
      audioSrc: 'audio/tomato.mp3',
    },
    {
      word: 'cucumber',
      translation: 'огурец',
      image: 'img/cucumber.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('cucumber'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('cucumber'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('cucumber'))),
      audioSrc: 'audio/cucumber.mp3',
    },
    {
      word: 'bread',
      translation: 'хлеб',
      image: 'img/bread.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('bread'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('bread'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('bread'))),
      audioSrc: 'audio/bread.mp3',
    },
    {
      word: 'butter',
      translation: 'масло',
      image: 'img/butter.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('butter'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('butter'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('butter'))),
      audioSrc: 'audio/butter.mp3',
    },
    {
      word: 'milk',
      translation: 'молоко',
      image: 'img/milk.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('milk'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('milk'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('milk'))),
      audioSrc: 'audio/milk.mp3',
    },
    {
      word: 'juice',
      translation: 'сок',
      image: 'img/juice.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('juice'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('juice'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('juice'))),
      audioSrc: 'audio/juice.mp3',
    },
    {
      word: 'eggs',
      translation: 'яйца',
      image: 'img/eggs.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('eggs'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('eggs'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('eggs'))),
      audioSrc: 'audio/eggs.mp3',
    },
    {
      word: 'chocolate',
      translation: 'шоколад',
      image: 'img/chocolate.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('chocolate'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('chocolate'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('chocolate'))),
      audioSrc: 'audio/chocolate.mp3',
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      image: 'img/skirt.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('skirt'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('skirt'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('skirt'))),
      audioSrc: 'audio/skirt.mp3',
    },
    {
      word: 'pants',
      translation: 'брюки',
      image: 'img/pants.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('pants'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('pants'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('pants'))),
      audioSrc: 'audio/pants.mp3',
    },
    {
      word: 'blouse',
      translation: 'блузка',
      image: 'img/blouse.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('blouse'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('blouse'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('blouse'))),
      audioSrc: 'audio/blouse.mp3',
    },
    {
      word: 'dress',
      translation: 'платье',
      image: 'img/dress.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('dress'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('dress'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('dress'))),
      audioSrc: 'audio/dress.mp3',
    },
    {
      word: 'boot',
      translation: 'ботинок',
      image: 'img/boot.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('boots'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('boots'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('boots'))),
      audioSrc: 'audio/boot.mp3',
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      image: 'img/shirt.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('shirt'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('shirt'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('shirt'))),
      audioSrc: 'audio/shirt.mp3',
    },
    {
      word: 'coat',
      translation: 'пальто',
      image: 'img/coat.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('coat'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('coat'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('coat'))),
      audioSrc: 'audio/coat.mp3',
    },
    {
      word: 'shoe',
      translation: 'туфли',
      image: 'img/shoe.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('shoe'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('shoe'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('shoe'))),
      audioSrc: 'audio/shoe.mp3',
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      image: 'img/sad.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('sad'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('sad'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('sad'))),
      audioSrc: 'audio/sad.mp3',
    },
    {
      word: 'angry',
      translation: 'сердитый',
      image: 'img/angry.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('angry'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('angry'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('angry'))),
      audioSrc: 'audio/angry.mp3',
    },
    {
      word: 'happy',
      translation: 'счастливый',
      image: 'img/happy.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('happy'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('happy'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('happy'))),
      audioSrc: 'audio/happy.mp3',
    },
    {
      word: 'tired',
      translation: 'уставший',
      image: 'img/tired.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('tired'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('tired'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('tired'))),
      audioSrc: 'audio/tired.mp3',
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      image: 'img/surprised.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('surprised'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('surprised'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('surprised'))),
      audioSrc: 'audio/surprised.mp3',
    },
    {
      word: 'scared',
      translation: 'испуганный',
      image: 'img/scared.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('scared'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('scared'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('scared'))),
      audioSrc: 'audio/scared.mp3',
    },
    {
      word: 'smile',
      translation: 'улыбка',
      image: 'img/smile.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('smile'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('smile'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('smile'))),
      audioSrc: 'audio/smile.mp3',
    },
    {
      word: 'laugh',
      translation: 'смех',
      image: 'img/laugh.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('laugh'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('laugh'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('laugh'))),
      audioSrc: 'audio/laugh.mp3',
    },
  ],
  [
    {
      word: 'bed',
      translation: 'кровать',
      image: 'img/bed.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('bed'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('bed'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('bed'))),
      audioSrc: 'audio/bed.mp3',
    },
    {
      word: 'table',
      translation: 'стол',
      image: 'img/table.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('table'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('table'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('table'))),
      audioSrc: 'audio/table.mp3',
    },
    {
      word: 'chair',
      translation: 'стул',
      image: 'img/chair.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('chair'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('chair'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('chair'))),
      audioSrc: 'audio/chair.mp3',
    },
    {
      word: 'house',
      translation: 'дом',
      image: 'img/house.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('house'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('house'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('house'))),
      audioSrc: 'audio/house.mp3',
    },
    {
      word: 'kitchen',
      translation: 'кухня',
      image: 'img/kitchen.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('kitchen'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('kitchen'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('kitchen'))),
      audioSrc: 'audio/kitchen.mp3',
    },
    {
      word: 'bathroom',
      translation: 'ванная комната',
      image: 'img/bathroom.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('bathroom'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('bathroom'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('bathroom'))),
      audioSrc: 'audio/bathroom.mp3',
    },
    {
      word: 'carpet',
      translation: 'ковер',
      image: 'img/carpet.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('carpet'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('carpet'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('carpet'))),
      audioSrc: 'audio/carpet.mp3',
    },
    {
      word: 'picture',
      translation: 'картина',
      image: 'img/picture.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('picture'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('picture'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('picture'))),
      audioSrc: 'audio/picture.mp3',
    },
  ],
  [
    {
      word: 'river',
      translation: 'река',
      image: 'img/river.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('river'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('river'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('river'))),
      audioSrc: 'audio/river.mp3',
    },
    {
      word: 'moon',
      translation: 'луна',
      image: 'img/moon.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('moon'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('moon'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('moon'))),
      audioSrc: 'audio/moon.mp3',
    },
    {
      word: 'cloud',
      translation: 'облако',
      image: 'img/cloud.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('cloud'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('cloud'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('cloud'))),
      audioSrc: 'audio/cloud.mp3',
    },
    {
      word: 'sun',
      translation: 'солнце',
      image: 'img/sun.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('sun'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('sun'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('sun'))),
      audioSrc: 'audio/sun.mp3',
    },
    {
      word: 'flower',
      translation: 'цветок',
      image: 'img/flower.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('flower'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('flower'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('flower'))),
      audioSrc: 'audio/flower.mp3',
    },
    {
      word: 'tree',
      translation: 'дерево',
      image: 'img/tree.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('tree'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('tree'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('tree'))),
      audioSrc: 'audio/tree.mp3',
    },
    {
      word: 'grass',
      translation: 'трава',
      image: 'img/grass.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('grass'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('grass'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('grass'))),
      audioSrc: 'audio/grass.mp3',
    },
    {
      word: 'rainbow',
      translation: 'радуга',
      image: 'img/rainbow.jpg',
      counter: countClicks(JSON.parse(localStorage.getItem('rain'))),
      right: rightClicksCount(JSON.parse(localStorage.getItem('rain'))),
      wrong: wrongClicksCount(JSON.parse(localStorage.getItem('rain'))),
      audioSrc: 'audio/rainbow.mp3',
    },
  ],
];

// eslint-disable-next-line import/prefer-default-export
export { cards };
