export const ACTIONS = {

  TEXT_ENTERED: 'new todo was entered',
  TODO_LIST_CHANGED:'todolist was changed',
  TODO_CREATED:'todo was created',
  RESET_SELECT_ALL:'select-all is empty',
  TODOS_MODIFIED: 'data was modified',
  NEW_STATUS: 'status was changed',
  TODO_DELETED:'solitary todo was removed',
  TODO_CHECKED_CHANGED:'state of todo was changed',
  STATUS_SET:'new status was set',
  SELECT_ALL_CHANGED:'select-all input was changed',
  DATE_CLICKED:'date area was clicked',
  NO_COMPLETED_TODOS: 'no completed todos',
  EDITION_FIELD_ADDED:"edition fild was added",
  TODO_EDITED: 'todo was edited',
  COMPLETED_DELETED: 'completed todos were deleted',
  DELETE_COMPLETED: 'completed data to delete',
  TABLE_CLICKED: 'table was clicked',
  TABLE_DBLCLICKED: 'table was double clicked',
  DATE_CLICKED: 'table head "Date" was clicked',
  COUNTER_CHANGED: 'counter was changed',
  LEAVE_PAGE: 'end current session',

};
